### ISSUE TITLE
Running node-w3c-validator throw error

### ISSUE THREAD

**Issue by forethoughtde** [dutchenkoOleg/node-w3c-validator#3]
This is following error message

```
⠴ node-w3c-validator - processing ...undefined:1
{"messages":[{"type":"error","url":"file:/vagrant/var/export/ernaehrung_rezepte.html","lastLine":37,"lastColumn":36,"firstColumn":21,"message":"Bad value “” for attribute “action” on element “form”: Must be non-empty.","extract":"          <form action=\"\">\n     ","hiliteStart":10,"hiliteLength":16},{"type":"error","url":"file:/vagrant/var/export/ernaehrung_rezepte.html","lastLine":39,"lastColumn":68,"firstColumn":29,"message":"Any “input” descendant of a “label” element with a “for” attribute must have an ID value that matches that “for” attribute.","extract":"          <input type=\"text\" name=\"chargennummer\">\n     ","hiliteStart":10,"hiliteLength":40},{"type":"error","url":"file:/vagrant/var/export/ernaehrung_rezepte.html","lastLine":50,"lastColumn":40,"firstColumn":25,"message":"Bad value “” for attribute “action” on element “form”: Must be non-empty.","extract":"          <form action=\"\">\n     ","hiliteStart":10,"hiliteLength":16},{"type":"er

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at renderHtml (/vagrant/node_modules/node-w3c-validator/lib/render-html.js:56:22)
    at /vagrant/node_modules/node-w3c-validator/lib/validator.js:162:14
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

```

**Comment by dutchenkoOleg** [comment]
@forethoughtde Hi!

can you attach your "ernaehrung_rezepte.html" file? for several tests

**Comment by forethoughtde** [comment]
@dutchenkoOleg There were two problems;  The first one was form element had an empty **action** and no method attribute and the second problem was non-exist value used in **for** attribute in label.

**Comment by dutchenkoOleg** [comment]
@forethoughtde I tested node-w3c-validator with this markup

```html
<form id="test-1" action="">
    <label for></label>
</form>

<form id="test-2" action>
    <label for="non-exist-1">Lorem ipsum</label>
</form>

<form id="test-3" action>
    <label for="non-exist-2">
        <input type="checkbox">
    </label>
</form>

<form id="test-4" method="get">
    <label for>
        <input type="checkbox">
    </label>
    <label for="non-exist-1">Lorem ipsum</label>
    <label for="non-exist-2">
        <input type="checkbox">
    </label>
</form>
```

and had no same error in process as yours.  

Can you share part of your markup, in which you suppose problems?  
Also, can you provide information:

- your `DOCTYPE`, 
- charset of the testing document
 - and options that you used for configuration node-w3c-validator

**Comment by dutchenkoOleg** [comment]
Closed for now.
@forethoughtde feel free to re-open issue if still need
